version: 2

models:

    - name: stg_token_transfers
      columns:
       - name: transaction_hash
         data_tests:
          - relationships:
              to: ref('stg_transactions')
              field: hash

    - name: int_transactions_enriched
      columns:
       - name: value
         data_tests:
          - assert_value_amount_not_negative:
              field: block_number
         
    - name: stg_transactions
      description: Transactions in the Ethereum Blockchain
      columns:
       - name: hash
         tags: ['keys']
         description: This is a very long multiline description about the unique
           identifier of each transaction in the Ethereum blockchain
         data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_token_transfers')
              field: transaction_hash
              severity: warn
              config:
                store_failures: true
                store_failures_as: table
                where: date > current_date - 25

    - name: fct_stablecoin_activity_per_day
      latest_version: 2
      config:
        contract:
          enforced: true
          alias_types: true
      columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: varchar
        description: ""

      - name: symbol
        data_type: varchar
        description: ""

      - name: type
        data_type: varchar
        description: ""
        data_tests:
          - accepted_values:
              values: ['Hybrid', 'Crypto-backed', 'Fiat-backed']

      - name: total_daily_value
        data_type: float
        description: ""
     
      versions:
      - v: 1
        # Matches what's above -- nothing more needed
      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [token_address, symbol]


unit_tests:
  - name: test_is_valid_transaction_category_breakdown
    model: int_transactions_enriched
    overrides:
      macros:
        # unit test this model in "full refresh" mode
        is_incremental: false 
    given:
      - input: ref('stg_transactions')
        rows:
          - {receipt_contract_address: 'bla'}

      - input: ref('stg_token_transfers')
        rows:
          - {transaction_hash: 'bla'}

    expect:
      rows:
        - {transaction_category: 'contract_creation'}