version: 2

sources:
  - name: eth
    description: here is my ETH source
    database: eth  
    schema: eth_schema 
    freshness: 
      warn_after: {count: 12, period: hour}
      error_after: {count: 40, period: day} 
    loaded_at_field: to_timestamp(date) 
    tables:
      - name: contracts
        description: this is my contracts table
      - name: contracts_clone
      - name: token_transfers
      - name: transactions
        columns:
          - name: hash
            data_tests:
              - unique
  
            
    